//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Sample.Controllers.Status;
using System.Text.Json.Serialization;

namespace Sample;

[JsonSerializable(typeof(GenericRootCheckEndpointResponse<int>))]
[JsonSerializable(typeof(GenericRootCheckEndpointResponse<string>))]
[JsonSerializable(typeof(GenericRootCheckEndpointResponse<System.DateTime>))]
[JsonSerializable(typeof(MultipleGenericRootCheckEndpointResponse<int, DateTime>))]
[JsonSerializable(typeof(MultipleGenericRootCheckEndpointResponse<string, int>))]
[JsonSerializable(typeof(RootCheckEndpointResponse))]
internal partial class AppJsonSerializerContext : JsonSerializerContext
{
}
